Repository ManageIQ/linux_admin, pull requests merged in 2024-08, with the labels that each got.

#252 Fix rubocop warnings in NetworkInterface Spec
  spec/network_interface_spec.rb
Labels: test

#249 Add LinuxAdmin::NetworkInterface.list
  lib/linux_admin/network_interface.rb
  spec/network_interface_spec.rb
Labels: enhancement

#250 Use ruby 3.1 for code coverage
  .github/workflows/ci.yaml
Labels: developer, test

#251 Use --json for ip command output
  lib/linux_admin/network_interface.rb
  spec/network_interface_spec.rb
Labels: refactoring

#254 Add network interface loopback
  lib/linux_admin/network_interface.rb
Labels: enhancement
